const BASE_COLUMN_COUNT = 11;
const QUANTITY_COLUMNS_COUNT = 2;
const CHUNK_SIZE = 10;
const STANDARD_DPI = 96;
const BASE_SCALE_FACTOR = 400;
const SCALE_FACTOR = STANDARD_DPI / BASE_SCALE_FACTOR;
const NAME_COLUMN_WIDTH = 50;
const BASE_COLUMN_WIDTH = 15;
const EXTRA_WIDTH_FOR_NUMERIC = 2;

const excelConstants = {
    BASE_COLUMN_COUNT,
    QUANTITY_COLUMNS_COUNT,
    CHUNK_SIZE,
    SCALE_FACTOR,
    NAME_COLUMN_WIDTH,
    BASE_COLUMN_WIDTH,
    EXTRA_WIDTH_FOR_NUMERIC
};

export default excelConstants;
